module.exports = [
  {
  'name': 'Chase Sapphire Preferred Credit Card',
  'cardType': 'Chase',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'General Points',
  'program': 'Chase Ultimate Rewards',
  'signupBonus': 50000,
  'minSpend': 4000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/204650/599890.png'
  },
  {
  'name': 'Marriott Rewards Credit Card',
  'cardType': 'Visa',
  'benefit': 'One free night stay annually',
  'annFeeAmt': 85,
  'waivedFees': false,
  'category': 'Hotel Points',
  'program': 'Marriott Rewards',
  'signupBonus': 80000,
  'minSpend': 3000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/220564/605681.png'
  },
  {
  'name': 'Citi DoubleCash Card',
  'cardType': 'Citi',
  'benefit': 'Earn 2% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/220264/602414.png'
  },
  {
  'name': 'Capital One Venture Card',
  'cardType': 'Capital One',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 59,
  'waivedFees': true,
  'category': 'Miles',
  'program': 'Capital One Miles',
  'signupBonus': 40000,
  'minSpend': 3000,
  'cardImg': 'http://media.linkoffers.com/200x200/capital-one-venture-rewards-credit-card-101614.png'
  },
  {
  'name': 'Citi Prestige Credit Card',
  'cardType': 'Citi',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 450,
  'waivedFees': false,
  'category': 'General Points',
  'program': 'Citi ThankYou Rewards',
  'signupBonus': 50000,
  'minSpend': 5000,
  'cardImg': 'http://content.linkoffers.net/SharedImages/Products/220307/603102.png'
  },
  {
  'name': 'Discover It Card',
  'cardType': 'Discover',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://travelwithmiles.com/wp-content/uploads/2012/07/Discover-Card.png'
  },
  {
  'name': 'Chase Freedom Credit Card',
  'cardType': 'Visa',
  'benefit': '5% rewards on rotating categories',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Chase Ultimate Rewards',
  'signupBonus': 150,
  'minSpend': 500,
  'cardImg': 'http://savingsbeagle.com/wp-content/uploads/2015/11/599919.png'
  },
  {
  'name': 'Fidelity Rewards Visa Signature Card',
  'cardType': 'Visa',
  'benefit': 'Get 2% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Fidelity',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'https://www.fidelity.com/bin-public/060_www_fidelity_com/images/fidelity_rewards_cc.jpg' // needs resizing
  },
  {
  'name': 'IHG Rewards Credit Card',
  'cardType': 'MasterCard',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 49,
  'waivedFees': true,
  'category': 'Hotel Points',
  'program': 'IHG Rewards Club',
  'signupBonus': 60000,
  'minSpend': 1000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/220367/603643.png'
  },
  {
  'name': 'Chase Ink Cash Business Credit Card',
  'cardType': 'Chase',
  'benefit': 'Get 1% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 300,
  'minSpend': 3000,
  'cardImg': 'http://content.linkoffers.net/SharedImages/Products/209475/598222.png'
  },
  {
  'name': 'Hyatt Credit Card',///////************************************
  'cardType': 'Visa',
  'benefit': '2 free nights',
  'annFeeAmt': 75,
  'waivedFees': false,
  'category': 'Hotel Points',
  'program': 'Hyatt Gold Passport',
  'signupBonus': 0,
  'minSpend': 2000,
  'cardImg': 'http://www.creditcardquestions.com/wp-content/uploads/2015/05/Chase-Hyatt-Credit-Card.jpg'
  },
  {
  'name': 'Southwest Rapid Rewards Plus Visa Credit Card', ////////**************************
  'cardType': 'Visa',
  'benefit': '3000 points annually',
  'annFeeAmt': 69,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'Southwest Rapid Rewards',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'https://creditcards.chase.com/R-SWA/6000381/images/hp_plus_card.png'
  },
  {
  'name': 'Southwest Rapid Rewards Premier Visa Credit Card',
  'cardType': 'Visa',
  'benefit': '6000 points annually with no foreign transaction fees',
  'annFeeAmt': 99,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'Southwest Rapid Rewards',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://content.linkoffers.net/SharedImages/Products/209558/600362.png'
  },
  {
  'name': 'Blue Cash Preferred Card',
  'cardType': 'American Express',
  'benefit': 'Get 1% cash back',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 250,
  'minSpend': 1000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/165588/603471.png'
  },
  {
  'name': 'Sallie Mae Upromise MasterCard',
  'cardType': 'MasterCard',
  'benefit': 'Get 1% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 25,
  'cardImg': 'https://gif.barclaycardus.com/apply/img/upa/credit/plastics/UPA_masterCard.png' // needs resizing
  },
  {
  'name': 'BankAmericard Travel Rewards Credit Card',
  'cardType': 'Visa',
  'benefit': '1.5 points for every dollar spent',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Travel points',
  'program': 'Bank of America Preferred Rewards',
  'signupBonus': 20000,
  'minSpend': 1000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/209868/604904.png'
  },
  {
  'name': 'Capital One Quicksilver Cash Rewards Credit Card',
  'cardType': 'Visa',
  'benefit': 'Get 1.5% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 100,
  'minSpend': 500,
  'cardImg': 'http://media.linkoffers.com/200x200/capital-one-quicksilver-cash-rewards-credit-card-040815.png'
  },
  {
  'name': 'Wells Fargo Cash Wise Visa Card',
  'cardType': 'Visa',
  'benefit': 'Get 1.5% cash back',
  'annFeeAmt': '0',
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'https://www04.wellsfargomedia.com/assets/images/photography/product/290x150/cash_back_college_visa_card.png' // needs resizing
  },
  {
  'name': 'Chase Freedom Unlimited Card',
  'cardType': 'Visa',
  'benefit': 'Get 1.5 % cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 150,
  'minSpend': 500,
  'cardImg': 'https://applynow.chase.com/FlexAppWeb/image/06610_card_C0002_RSP.png' //needs resizing
  },
  {
  'name': 'BankAmericard Cash Rewards Credit Cards',
  'cardType': 'Visa',
  'benefit': 'Get 1% cash back on up to $2500 spend per quarter',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 100,
  'minSpend': 500,
  'cardImg': 'http://promo.bankofamerica.com/mobile/ccsearchlp6/assets/images/60fd9a71.cardart_cash.png'
  },
  {
  'name': 'Chase British Airways Visa Signature Card',
  'cardType': 'Visa',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'Avios Points',
  'program': 'Avios',
  'signupBonus': 50000,
  'minSpend': 3000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/218528/603035.png'
  },
  {
  'name': 'Barclays Arrival Plus World Elite MasterCard',
  'cardType': 'MasterCard',
  'benefit': 'Get 2x miles on every purchase',
  'annFeeAmt': 89,
  'waivedFees': true,
  'category': 'Travel Points',
  'program': 'Barclay',
  'signupBonus': 50000,
  'minSpend': 3000,
  'cardImg': 'http://content.linkoffers.net/SharedImages/Products/217189/605947.png'
  },
  {
  'name': 'Barclays JetBlue Plus Card',
  'cardType': 'MasterCard',
  'benefit': 'Get 5000 bonus points annually',
  'annFeeAmt': 99,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'JetBlue TrueBlue',
  'signupBonus': 30000,
  'minSpend': 1000,
  'cardImg': 'http://content.linkoffers.net/SharedImages/Products/220678/607513.png'
  },
  {
  'name': 'Citi Hilton HHonors Reserve Credit Card',
  'cardType': 'Visa',
  'benefit': 'Hilton gold membership and two free nights after meeting minimum spend',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'HHonors',
  'signupBonus': 0,
  'minSpend': 2500,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/198429/598688.png'
  },
  {
  'name': 'Starwood Preferred Guest Credit Card',
  'cardType': 'American Express',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 95,
  'waivedFees': true,
  'category': 'Travel Points',
  'program': 'Starpoints',
  'signupBonus': 30000,
  'minSpend': 3000,
  'cardImg': 'http://content.linkoffers.net/sharedimages/products/70/605863.png'
  }
]
