module.exports = [
  {
  'name': 'Chase Sapphire Preferred',
  'cardType': 'Chase',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'General Points',
  'program': 'Chase Ultimate Rewards',
  'signupBonus': 50000,
  'minSpend': 4000,
  'cardImg': 'http://localhost:4000/cardPics/chaseSapphire.png'
  },
  {
  'name': 'Marriott Rewards',
  'cardType': 'Visa',
  'benefit': 'One free night stay annually',
  'annFeeAmt': 85,
  'waivedFees': false,
  'category': 'Hotel Points',
  'program': 'Marriott Rewards',
  'signupBonus': 80000,
  'minSpend': 3000,
  'cardImg': 'http://localhost:4000/cardPics/marriottRewards.png'
  },
  {
  'name': 'Citi DoubleCash',
  'cardType': 'Citi',
  'benefit': 'Earn 2% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://localhost:4000/cardPics/citiDouble.png'
  },
  {
  'name': 'Capital One Venture',
  'cardType': 'Capital One',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 59,
  'waivedFees': true,
  'category': 'Miles',
  'program': 'Capital One Miles',
  'signupBonus': 40000,
  'minSpend': 3000,
  'cardImg': 'http://localhost:4000/cardPics/capOneVenture.png'
  },
  {
  'name': 'Citi Prestige',
  'cardType': 'Citi',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 450,
  'waivedFees': false,
  'category': 'General Points',
  'program': 'Citi ThankYou Rewards',
  'signupBonus': 50000,
  'minSpend': 5000,
  'cardImg': 'http://localhost:4000/cardPics/citiPrestige.png'
  },
  {
  'name': 'Discover It',
  'cardType': 'Discover',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://localhost:4000/cardPics/discoverIt.png'
  },
  {
  'name': 'Chase Freedom',
  'cardType': 'Visa',
  'benefit': '5% rewards on rotating categories',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Chase Ultimate Rewards',
  'signupBonus': 150,
  'minSpend': 500,
  'cardImg': 'http://localhost:4000/cardPics/chaseFreedom.png'
  },
  {
  'name': 'Fidelity Rewards Visa Signature',
  'cardType': 'Visa',
  'benefit': 'Get 2% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Fidelity',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://localhost:4000/cardPics/fidelityRewardsTransparent.png' // needs resizing
  },
  {
  'name': 'IHG Rewards',
  'cardType': 'MasterCard',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 49,
  'waivedFees': true,
  'category': 'Hotel Points',
  'program': 'IHG Rewards Club',
  'signupBonus': 60000,
  'minSpend': 1000,
  'cardImg': 'http://localhost:4000/cardPics/IHGRewards.png'
  },
  {
  'name': 'Chase Ink Cash Business',
  'cardType': 'Chase',
  'benefit': 'Get 1% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 300,
  'minSpend': 3000,
  'cardImg': 'http://localhost:4000/cardPics/chaseInk.png'
  },
  {
  'name': 'Chase Hyatt',
  'cardType': 'Visa',
  'benefit': '2 free nights',
  'annFeeAmt': 75,
  'waivedFees': false,
  'category': 'Hotel Points',
  'program': 'Hyatt Gold Passport',
  'signupBonus': 0,
  'minSpend': 2000,
  'cardImg': 'http://localhost:4000/cardPics/hyattVisa.png'
  },
  {
  'name': 'Southwest Rapid Rewards Plus Visa',
  'cardType': 'Visa',
  'benefit': '3000 points annually',
  'annFeeAmt': 69,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'Southwest Rapid Rewards',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://localhost:4000/cardPics/southwestPlus.png'
  },
  {
  'name': 'Southwest Rapid Rewards Premier Visa',
  'cardType': 'Visa',
  'benefit': '6000 points annually with no foreign transaction fees',
  'annFeeAmt': 99,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'Southwest Rapid Rewards',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://localhost:4000/cardPics/southwestPremier.png'
  },
  {
  'name': 'Blue Cash Preferred',
  'cardType': 'American Express',
  'benefit': 'Get 1% cash back',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 250,
  'minSpend': 1000,
  'cardImg': 'http://localhost:4000/cardPics/amExCashTransparent.png'
  },
  {
  'name': 'Sallie Mae Upromise MasterCard',
  'cardType': 'MasterCard',
  'benefit': 'Get 1% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 25,
  'cardImg': 'http://localhost:4000/cardPics/sallieMae.png'
  },
  {
  'name': 'BankAmericard Travel Rewards',
  'cardType': 'Visa',
  'benefit': '1.5 points for every dollar spent',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Travel points',
  'program': 'Bank of America Preferred Rewards',
  'signupBonus': 20000,
  'minSpend': 1000,
  'cardImg': 'http://localhost:4000/cardPics/boaTravel.png'
  },
  {
  'name': 'Capital One Quicksilver Cash Rewards',
  'cardType': 'Visa',
  'benefit': 'Get 1.5% cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 100,
  'minSpend': 500,
  'cardImg': 'http://localhost:4000/cardPics/capOneQuicksilver.png'
  },
  {
  'name': 'Wells Fargo Cash Wise Visa',
  'cardType': 'Visa',
  'benefit': 'Get 1.5% cash back',
  'annFeeAmt': '0',
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 0,
  'minSpend': 0,
  'cardImg': 'http://localhost:4000/cardPics/wellsFargoCashWise.png'
  },
  {
  'name': 'Chase Freedom Unlimited',
  'cardType': 'Visa',
  'benefit': 'Get 1.5 % cash back',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 150,
  'minSpend': 500,
  'cardImg': 'http://localhost:4000/cardPics/chaseFreedomUnlimited.png'
  },
  {
  'name': 'BankAmericard Cash Rewards',
  'cardType': 'Visa',
  'benefit': 'Get 1% cash back on up to $2500 spend per quarter',
  'annFeeAmt': 0,
  'waivedFees': false,
  'category': 'Cash Back',
  'program': 'Cash',
  'signupBonus': 100,
  'minSpend': 500,
  'cardImg': 'http://localhost:4000/cardPics/boaCash.png'
  },
  {
  'name': 'Chase British Airways Visa Signature',
  'cardType': 'Visa',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'Avios Points',
  'program': 'Avios',
  'signupBonus': 50000,
  'minSpend': 3000,
  'cardImg': 'http://localhost:4000/cardPics/britishAirways.png'
  },
  {
  'name': 'Barclays Arrival Plus World Elite MasterCard',
  'cardType': 'MasterCard',
  'benefit': 'Get 2x miles on every purchase',
  'annFeeAmt': 89,
  'waivedFees': true,
  'category': 'Travel Points',
  'program': 'Barclay',
  'signupBonus': 50000,
  'minSpend': 3000,
  'cardImg': 'http://localhost:4000/cardPics/barclayPlus.png'
  },
  {
  'name': 'Barclays JetBlue Plus',
  'cardType': 'MasterCard',
  'benefit': 'Get 5000 bonus points annually',
  'annFeeAmt': 99,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'JetBlue TrueBlue',
  'signupBonus': 30000,
  'minSpend': 1000,
  'cardImg': 'http://localhost:4000/cardPics/jetBlue.png'
  },
  {
  'name': 'Citi Hilton HHonors Reserve',
  'cardType': 'Visa',
  'benefit': 'Hilton gold membership and two free nights after meeting minimum spend',
  'annFeeAmt': 95,
  'waivedFees': false,
  'category': 'Travel Points',
  'program': 'HHonors',
  'signupBonus': 0,
  'minSpend': 2500,
  'cardImg': 'http://localhost:4000/cardPics/hhonors.png'
  },
  {
  'name': 'Starwood Preferred Guest',
  'cardType': 'American Express',
  'benefit': 'No foreign transaction fees',
  'annFeeAmt': 95,
  'waivedFees': true,
  'category': 'Travel Points',
  'program': 'Starpoints',
  'signupBonus': 30000,
  'minSpend': 3000,
  'cardImg': 'http://localhost:4000/cardPics/spg.png'
  }
]
